from typing import Any, Callable

def set_appearance_mode(mode: str) -> None: ...
def set_default_color_theme(theme: str) -> None: ...

class CTk:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def title(self, text: str) -> None: ...
    def geometry(self, geometry: str) -> None: ...
    def after(self, ms: int, func: Callable[..., Any]) -> None: ...
    def mainloop(self) -> None: ...
    def minsize(self, width: int, height: int) -> None: ...
    def protocol(self, name: str, func: Callable[..., Any]) -> None: ...
    def grid_rowconfigure(self, index: int, **kwargs: Any) -> None: ...
    def grid_columnconfigure(self, index: int, **kwargs: Any) -> None: ...
    def destroy(self) -> None: ...
    def bind(self, sequence: str, func: Callable[..., Any]) -> None: ...

class CTkToplevel:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def title(self, text: str) -> None: ...
    def geometry(self, geometry: str) -> None: ...
    def clipboard_clear(self) -> None: ...
    def clipboard_append(self, text: str) -> None: ...
    def destroy(self) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...

class CTkFrame:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def pack_propagate(self, flag: bool) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...

class CTkLabel:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...

class CTkEntry:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def insert(self, index: Any, text: Any) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...

class CTkButton:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...

class CTkTextbox:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def insert(self, index: Any, text: Any, tags: Any | None = None) -> None: ...
    def see(self, index: Any) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...
    def tag_config(self, tag_name: str, **kwargs: Any) -> None: ...

class CTkComboBox:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def get(self) -> str: ...
    def set(self, value: str) -> None: ...

class CTkCheckBox:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...
    def get(self) -> int: ...

class CTkTabview:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def add(self, name: str) -> Any: ...
    def tab(self, name: str) -> Any: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...

class CTkFont:
    def __init__(self, family: str | None = None, size: int | None = None, weight: str | None = None) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...